### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by 5XS** [anxety-solo/sd-webui-sagemaker#7]
```
Segmentation fault (core dumped)

⌚️ Вы проводите эту сессию в течение - 0:02:01

```

sdwebui попросту не запускается

версия анред

**Comment by anxety-solo** [comment]
Проверил и не обнаружил никаких проблем.

Это весь вывод при запуске? 
Возникло это после перехода на версию "anred" или нет?
Пробовали ли вы удалить весь блокнот и установить его по новой с нуля?

**Comment by 5XS** [comment]
> Проверил и не обнаружил никаких проблем.
> 
> Это весь вывод при запуске? Возникло это после перехода на версию "anred" или нет? Пробовали ли вы удалить весь блокнот и установить его по новой с нуля?

удалил все, сработало. Только почему-то при первом запуске заполняет весь диск и выдает ошибку, которую можно исправить очисткой ненужных файлов
